"""Prints Table IV (Section VI-E): sim-to-real detection AUC.

Data: results/multi_classifier_10dB.json (generated by run_benchmark.py).
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import bold_max, load_json, print_latex_table

RESULTS_PATH = Path(__file__).resolve().parent.parent / "results" / "multi_classifier_10dB.json"

# JSON key -> (display label, is_simulation_model)
MODEL_MAP = [
    ("oracle",    r"Oracle (real)",                    False),
    ("M_QTC",     r"M\textsubscript{QTC}",             True),
    ("M6_Copula", r"M\textsubscript{3}",               True),
    ("M3_Hybrid", r"M\textsubscript{2}",               True),
    ("M1_AWGN",   r"M\textsubscript{1} (AWGN)",       True),
]

CLASSIFIERS = ["LogReg", "SVM", "RF", "MLP", "AE"]
CLF_HEADERS = ["LR", "SVM", "RF", "MLP", "AE", "Mean"]
HEADERS = ["Training data"] + CLF_HEADERS

CAPTION = (
    r"Sim-to-real detection AUC at 10~dB in the laboratory "
    r"(per-device calibration, mean$\pm$std across 5 receivers, 3 seeds)."
)
LABEL = "tab:detection"

DEVICES = [
    "node-thermal-01",
    "node-acoustic-02",
    "node-infrared-03",
    "node-optical-04",
    "node-magnetic-05",
]


def _compute_device_mean_std(per_device: dict, model_key: str) -> tuple[float, float]:
    """Mean and std of per-device mean AUC across 5 receivers."""
    device_means = []
    for dev in DEVICES:
        dev_aucs = [
            per_device[dev][model_key][c]["auc_mean"] for c in CLASSIFIERS
        ]
        device_means.append(float(np.mean(dev_aucs)))
    return float(np.mean(device_means)), float(np.std(device_means, ddof=0))


def main() -> None:
    """Print Table IV: sim-to-real detection AUC."""
    if not RESULTS_PATH.exists():
        print(f"source data not found: {RESULTS_PATH}. Run `python run_benchmark.py`.")
        sys.exit(2)

    data = load_json(RESULTS_PATH)
    agg = data["mean_across_devices"]
    per_device = data["per_device"]

    # collect per-classifier AUC values (simulation models only, for bolding)
    sim_indices: list[int] = []
    all_aucs: dict[str, list[float]] = {c: [] for c in CLASSIFIERS}
    mean_aucs: list[float] = []
    mean_stds: list[float] = []

    for idx, (json_key, _, is_sim) in enumerate(MODEL_MAP):
        model_data = agg[json_key]
        m, s = _compute_device_mean_std(per_device, json_key)
        mean_aucs.append(m)
        mean_stds.append(s)
        for c in CLASSIFIERS:
            all_aucs[c].append(model_data[c]["auc_mean"])
        if is_sim:
            sim_indices.append(idx)

    def bold_best_sim(values: list[float], fmt: str = ".3f") -> list[str]:
        """Format values, bolding the max among simulation-model rows only."""
        sim_vals = [values[i] for i in sim_indices]
        best = max(sim_vals)
        out: list[str] = []
        for i, v in enumerate(values):
            s = f"{v:{fmt}}"
            if i in sim_indices and v == best:
                s = rf"\textbf{{{s}}}"
            out.append(s)
        return out

    formatted_clf: dict[str, list[str]] = {}
    for c in CLASSIFIERS:
        formatted_clf[c] = bold_best_sim(all_aucs[c])

    # format mean column with +/- std and bold-best
    mean_formatted = bold_best_sim(mean_aucs)
    formatted_mean_std: list[str] = []
    for i, s in enumerate(mean_formatted):
        std_str = f"{mean_stds[i]:.3f}"
        if r"\textbf{" in s:
            inner = s.replace(r"\textbf{", "").rstrip("}")
            formatted_mean_std.append(rf"\textbf{{{inner}$\pm${std_str}}}")
        else:
            formatted_mean_std.append(f"{s}$\\pm${std_str}")

    # build rows
    rows: list[list[str]] = []
    for i, (_, label, _) in enumerate(MODEL_MAP):
        row = [label]
        for c in CLASSIFIERS:
            row.append(formatted_clf[c][i])
        row.append(formatted_mean_std[i])
        rows.append(row)

    print_latex_table(
        headers=HEADERS,
        rows=rows,
        caption=CAPTION,
        label=LABEL,
        col_spec=r"lrrrrr|r",
        tabcolsep="5pt",
        midrule_after=[0],
    )


if __name__ == "__main__":
    main()
