"""Prints Table II (Section VI-A): within-scenario fidelity scores.

Data: results/controlled_20dB.json (generated by run_benchmark.py).
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import bold_min, load_json, print_latex_table

RESULTS_PATH = Path(__file__).resolve().parent.parent / "results" / "controlled_20dB.json"

# JSON key -> display label
MODEL_MAP = [
    ("M1_AWGN",    r"M\textsubscript{1} (AWGN)"),
    ("M3_Hybrid",  r"M\textsubscript{2} (Scaling)"),
    ("M6_Copula",  r"M\textsubscript{3} (Scaling+Corr)"),
    ("M_QTC",      r"M\textsubscript{QTC}"),
]

METRICS = ["amplitude", "phase", "temporal", "spectral", "aggregate"]
HEADERS = ["Model", "Ampl.", "Phase", "Temp.", "Spect.", "Aggr."]

CAPTION = (
    r"Within-scenario fidelity at 20~dB, controlled room "
    r"(mean$\pm$std, 5 seeds). Lower is better; phase is tied at this precision."
)
LABEL = "tab:within"


def main() -> None:
    """Print Table II: within-scenario fidelity."""
    if not RESULTS_PATH.exists():
        print(f"source data not found: {RESULTS_PATH}. Run `python run_benchmark.py`.")
        sys.exit(2)

    data = load_json(RESULTS_PATH)

    non_agg_metrics = [m for m in METRICS if m != "aggregate"]

    # collect raw metric values per column for bolding
    raw: dict[str, list[float]] = {m: [] for m in METRICS}
    agg_stds: list[float] = []
    for json_key, _ in MODEL_MAP:
        means = data[json_key]["mean"]
        stds = data[json_key]["std"]
        for m in METRICS:
            raw[m].append(means[m])
        agg_stds.append(stds["aggregate"])

    # format non-aggregate columns with bold-min
    fmts = {
        "amplitude": ".2f",
        "phase":     ".2f",
        "temporal":  ".2f",
        "spectral":  ".2f",
    }
    formatted_cols: dict[str, list[str]] = {}
    for m in non_agg_metrics:
        formatted_cols[m] = bold_min(raw[m], fmt=fmts[m])

    # format aggregate column as mean+/-std with bold-min
    agg_formatted = bold_min(raw["aggregate"], fmt=".2f")
    formatted_agg: list[str] = []
    for i, s in enumerate(agg_formatted):
        std_str = f"{agg_stds[i]:.2f}"
        if r"\textbf{" in s:
            inner = s.replace(r"\textbf{", "").rstrip("}")
            formatted_agg.append(rf"\textbf{{{inner}$\pm${std_str}}}")
        else:
            formatted_agg.append(f"{s}$\\pm${std_str}")

    # build rows
    rows: list[list[str]] = []
    for i, (_, label) in enumerate(MODEL_MAP):
        row = [label]
        for m in non_agg_metrics:
            row.append(formatted_cols[m][i])
        row.append(formatted_agg[i])
        rows.append(row)

    print_latex_table(
        headers=HEADERS,
        rows=rows,
        caption=CAPTION,
        label=LABEL,
    )


if __name__ == "__main__":
    main()
